### ISSUE TITLE
Client Crash when placing a tent

### ISSUE THREAD

**Issue by Error998** [Rikmuld/CampingMod-mcmod#13] opened 2015-01-18 13:48 UTC
The Camping Mod Version: 2.1c
Forge Version: 10.13.2.1236
Minecraft Version: 1.7.10
RailCraft Version: 9.4.0.0
Tested on Multiplayer

Steps to reproduce issue:
* Place a tent in the world

Result:
* Client crash
* [Client thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to com.rikmuld.camping.common.objs.tile.TileEntityMain

Crash Log: http://pastebin.com/LLd8QxAd

After logging in again tent is placed in the world and can be used.

**Comment by Rikmuld** [comment] 2015-01-18 15:13
Thank you for reporting the issue, it seems to be caused by the same thing as issue #11, it will be fixed in the next update.

**Comment by Rikmuld** [comment] 2015-01-18 17:28
Fixed tent placing

**Closed by Rikmuld** 2015-01-18 17:28 UTC
